// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTcjp2Z5t2-CbVNW3OwMCEVTHohtqdwfw',
    appId: '1:932560741113:web:573c1fbdf1be6ef8a1f828',
    messagingSenderId: '932560741113',
    projectId: 'fir-6f3fd',
    authDomain: 'fir-6f3fd.firebaseapp.com',
    storageBucket: 'fir-6f3fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUwRYJR8YJajVL8vN-JvWX2ym5x7Qvr08',
    appId: '1:932560741113:android:ef20434a0445f617a1f828',
    messagingSenderId: '932560741113',
    projectId: 'fir-6f3fd',
    storageBucket: 'fir-6f3fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3DSFT02q9Kz8L7T1-fzfcqnGA4bTJmnA',
    appId: '1:932560741113:ios:65c2ca6142ee85aea1f828',
    messagingSenderId: '932560741113',
    projectId: 'fir-6f3fd',
    storageBucket: 'fir-6f3fd.firebasestorage.app',
    iosBundleId: 'com.example.sigi',
  );
}
